import { gridToJson } from "./JSONparser";
import { reactive, readonly } from "vue";
import { useRoom } from "./useRoom";

/**
 * Interface to save street information
 * @param {String} streetType - Type of Street
 * @param {number} rotation - street rotation in degree
 * @param {number} posX - Position on x axis
 * @param {number} posY - Position on y axis
 */
export interface IStreetInformation {
  streetType: string;
  rotation: number;
  posX: number;
  posY: number;
}
/**
 * State that saves the information about the streets in an Array of IStreetInformation Objects
 */
const state = reactive({
  streets: Array<IStreetInformation>(),
});
/**
 * State Management for the streets
 * @see {@link updateStreetState} function that handles the onGridClickObject
 * @see {@link IStreetInformation} interface for the information saved in the state
 * @returns Returns the Array of streets (readonly) and the functions updateStreetState, isStreetPlaced and recieveNewStreetState,
 */
export function useStreets() {
  /**
   * Function of the State to handle the onGridClickObject.
   * If delete is selected the street in the array needs to be removed.
   * Otherwise the street needs to be saved.
   * @param {IStreetInformation} onGridClickObject - IStreetInformation Object that needs to be saved or deleted
   */
  function updateStreetState(onGridClickObject: IStreetInformation): void {
    if (onGridClickObject.streetType === "delete") {
      state.streets = state.streets.filter(
        (street) =>
          street.posX !== onGridClickObject.posX ||
          street.posY !== onGridClickObject.posY
      );
    } else {
      const foundStreet = state.streets.find(
        (street) =>
          street.posX === onGridClickObject.posX &&
          street.posY === onGridClickObject.posY
      );
      if (foundStreet) {
        foundStreet.rotation = onGridClickObject.rotation;
        foundStreet.streetType = onGridClickObject.streetType;
      } else {
        state.streets.push(onGridClickObject);
      }
    }
    gridToJson(state.streets);
  }

  /**
   * Sets our state to the new streets
   * @param {Array<IStreetInformation>} newStreets - Array of streets generated by our jsonToState-function
   */
  function recieveNewStreetState(newStreets: Array<IStreetInformation>) {
    state.streets = newStreets;
  }

  /**
   *
   * @param {number} row - row of the cell to be checked
   * @param {number} col - column of the cell to be checked
   * @returns boolean, if there is a street placed on the checked cell
   */
  function isStreetPlaced(row: number, col: number) {
    if (
      state.streets.find((street) => street.posX === row && street.posY === col)
    ) {
      return true;
    } else {
      return false;
    }
  }

  return {
    streets: readonly(state.streets),
    updateStreetState,
    isStreetPlaced,
    recieveNewStreetState,
  };
}
